# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='psot',
            new_name='post',
        ),
    ]
